/* AUTO-GENERATED FILE. DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found. It
 * should not be modified by hand.
 */

package com.example.ytdlp;

public final class R {
  public static final class color {
    public static final int background=0x7f010000;
    public static final int error=0x7f010001;
    public static final int inputBackground=0x7f010002;
    /**
     * YouTube Blue
     */
    public static final int onBackground=0x7f010003;
    public static final int onSurface=0x7f010004;
    public static final int onSurfaceVariant=0x7f010005;
    public static final int outline=0x7f010006;
    public static final int primary=0x7f010007;
    public static final int success=0x7f010008;
    public static final int surface=0x7f010009;
    public static final int surfaceVariant=0x7f01000a;
  }
  public static final class drawable {
    public static final int bubble_bg=0x7f020000;
    public static final int card_bg=0x7f020001;
    public static final int ic_home=0x7f020002;
    public static final int ic_settings=0x7f020003;
  }
  public static final class id {
    public static final int browser_progress_bar=0x7f030000;
    public static final int browser_progress_container=0x7f030001;
    public static final int browser_progress_text=0x7f030002;
    public static final int browser_url_input=0x7f030003;
    public static final int btn_browser_back=0x7f030004;
    public static final int btn_browser_download=0x7f030005;
    public static final int btn_browser_home=0x7f030006;
    public static final int btn_browser_refresh=0x7f030007;
    public static final int btn_browser_settings=0x7f030008;
    public static final int btn_copy_error=0x7f030009;
    public static final int btn_delete=0x7f03000a;
    public static final int btn_export=0x7f03000b;
    public static final int btn_fetch_info=0x7f03000c;
    public static final int btn_history_all=0x7f03000d;
    public static final int btn_history_audio=0x7f03000e;
    public static final int btn_history_video=0x7f03000f;
    public static final int btn_play=0x7f030010;
    public static final int btn_quick_download=0x7f030011;
    public static final int btn_restart=0x7f030012;
    public static final int btn_share=0x7f030013;
    public static final int clearBtn=0x7f030014;
    public static final int clear_btn=0x7f030015;
    public static final int content_frame=0x7f030016;
    public static final int copyBtn=0x7f030017;
    public static final int copy_btn=0x7f030018;
    public static final int dl_btn_mp3=0x7f030019;
    public static final int dl_btn_mp4=0x7f03001a;
    public static final int dl_loading_spinner=0x7f03001b;
    public static final int dl_preview_container=0x7f03001c;
    public static final int dl_quality_spinner=0x7f03001d;
    public static final int dl_thumbnail=0x7f03001e;
    public static final int dl_title=0x7f03001f;
    public static final int downloadBtn=0x7f030020;
    public static final int dynamic_island=0x7f030021;
    public static final int error_text=0x7f030022;
    public static final int history_grid=0x7f030023;
    public static final int history_tab_bar=0x7f030024;
    public static final int home_download_btn=0x7f030025;
    public static final int home_mp3_btn=0x7f030026;
    public static final int home_progress_bar=0x7f030027;
    public static final int home_url_input=0x7f030028;
    public static final int img_thumbnail=0x7f030029;
    public static final int input_bar=0x7f03002a;
    public static final int island_content=0x7f03002b;
    public static final int item_details=0x7f03002c;
    public static final int item_thumbnail=0x7f03002d;
    public static final int item_title=0x7f03002e;
    public static final int item_type_badge=0x7f03002f;
    public static final int kill_btn=0x7f030030;
    public static final int loading_spinner=0x7f030031;
    public static final int logScroll=0x7f030032;
    public static final int logView=0x7f030033;
    public static final int main_root=0x7f030034;
    public static final int manual_input=0x7f030035;
    public static final int nav_bar=0x7f030036;
    public static final int nav_browser=0x7f030037;
    public static final int nav_history=0x7f030038;
    public static final int nav_home=0x7f030039;
    public static final int nav_terminal=0x7f03003a;
    public static final int player_loader=0x7f03003b;
    public static final int player_title=0x7f03003c;
    public static final int preview_card=0x7f03003d;
    public static final int progressBar=0x7f03003e;
    public static final int progress_card=0x7f03003f;
    public static final int progress_percent=0x7f030040;
    public static final int progress_speed=0x7f030041;
    public static final int progress_title=0x7f030042;
    public static final int quality_spinner=0x7f030043;
    public static final int sel_btn_close=0x7f030044;
    public static final int sel_btn_mp3=0x7f030045;
    public static final int sel_btn_mp4=0x7f030046;
    public static final int sel_quality_spinner=0x7f030047;
    public static final int sel_thumbnail=0x7f030048;
    public static final int sel_title=0x7f030049;
    public static final int send_btn=0x7f03004a;
    public static final int set_btn_close=0x7f03004b;
    public static final int set_btn_save=0x7f03004c;
    public static final int set_debug_mode=0x7f03004d;
    public static final int set_home_url=0x7f03004e;
    public static final int state_browser=0x7f03004f;
    public static final int state_loading=0x7f030050;
    public static final int state_selection=0x7f030051;
    public static final int state_settings=0x7f030052;
    public static final int terminal_status=0x7f030053;
    public static final int txt_loading_anim=0x7f030054;
    public static final int txt_preview_title=0x7f030055;
    public static final int urlInput=0x7f030056;
    public static final int videoView=0x7f030057;
    public static final int webView=0x7f030058;
  }
  public static final class layout {
    public static final int activity_crash=0x7f040000;
    public static final int activity_main=0x7f040001;
    public static final int activity_player=0x7f040002;
    public static final int activity_terminal=0x7f040003;
    public static final int dialog_download=0x7f040004;
    public static final int layout_browser=0x7f040005;
    public static final int layout_history=0x7f040006;
    public static final int layout_home=0x7f040007;
    public static final int layout_logs=0x7f040008;
    public static final int list_item_history=0x7f040009;
  }
  public static final class string {
    public static final int app_name=0x7f050000;
    public static final int download_button=0x7f050001;
    public static final int url_hint=0x7f050002;
  }
  public static final class xml {
    public static final int provider_paths=0x7f060000;
  }
}